### ISSUE TITLE
CSS盒模型

### ISSUE THREAD

**Issue by lfb** [liangfengbo/css-layout-basics#2]
## 盒模型
- 包含：content，border，padding，margin，分为：标准模型 + IE模型
- 标准模型和IE模型的区别：
    - 计算高度和宽度的不同
    - 标准模型的宽高度不包括padding和border
    - IE模型的宽高包括padding和border
- 设置模型
    - 标准模型：box-sizing: contont-box （默认）
    - IE模型：box-sizing: border-box

## JS如何设置获取盒模型对应的宽和高
1. dom.style.width/height（只能取内联样式的宽高）
1. dom.currentStyle.width/height（拿到渲染的宽高，但只有IE支持）
1. window.getComputedStyle(dom).width/height（拿到渲染的宽高，兼容性好）
1. dom.getBoundingClientRect().width/height（计算一个元素的绝对位置）

## 外边距层叠
垂直方向上的两个外边距相遇时，会折叠成一个外边距，折叠后外边距的高度等于两者中最大的高度。

使用BFC解决外边距层叠的方案

## BFC
BFC(Block formatting context)直译为"块级格式化上下文"，它是一个独立的渲染区域。

## BFC的布局规则
1. 内部的Box会在垂直方向，一个接一个地放置。
1. Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生重叠
1. 每个元素的margin box的左边， 与包含块border box的左边相接触(对于从左往右的格式化，否则相反)。即使存在浮动也是如此。
1. BFC的区域不会与float box重叠。
1. BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素。反之也如此。
1. 计算BFC的高度时，浮动元素也参与计算

## 创建BFC
1. float 值不为 none
2. position为absolute或fixed
3. display属性为inline-block、table-cell、table-caption、flex、inline-flex
4. overflow 除了 visible 以外的值 (hidden、auto、scroll)

### 作用一：2栏布局
利BFC的布局规则第四条BFC的区域不会与float box重叠：
```html
<section class="box">
    <article class="left"></article>
    <article class="right"></article>
</section>
```
```css
.left {
    float: left;
    width: 200px;
    height: 100px;
    background: blue;
}

.right {
    /*创建BFC*/
    overflow: hidden;
    height: 300px;
    background: red;
}
```
### 作用二：清楚浮动
利用第六条计算 BFC 高度时，浮动元素也会参与计算：
```html
<ul class="parent">
    <li class="child"></li>
    <li class="child"></li>
</ul>
```
```css
.parent {
    /*创建BFC*/
    overflow: hidden;
    border: 5px solid red;
}

.child {
    width: 100px;
    height: 100px;
    float: left;
    border: 5px solid blue;
}
```
### 作用三：防止垂直margin重叠
利用第二条：属于同一个BFC的两个相邻Box的margin会发生重叠

```html 
<article class="box">box1</article>
<article class="box">box2</article>
```

```css
.box {
    width: 200px;
    line-height: 100px;
    text-align: center;
    margin: 100px;
    color: #f55;
    background: #fcc;
}
```

重新创建一个新的BFC就不会发生层叠了

```html
<article class="box">box1</article>

<section class="wrap">
    <article class="box">box2</article>
</section>
```
```css
.box {
    color: #f55;
    background: #fcc;
    width: 200px;
    line-height: 100px;
    text-align: center;
    margin: 100px;
}

.wrap {
    /*创建BFC*/
     overflow: hidden;
 }
```
