### ISSUE TITLE
CSS垂直居中

### ISSUE THREAD

**Issue by lfb** [liangfengbo/css-layout-basics#5]
## 垂直居中
```html
<ul class="parent">
    <li class="child">垂直居中</li>
</ul>
```

## 方法一
- 设置父元素为表格单元，再加个`vertical-align: middle;`
- 优点：简单
- 缺点：ie6，7不支持

```css
.parent {
    dispaly: table-cell;
    vertical-align: middle;
}

.child {
}
```

## 方法二
- 设置父元素为相对定位
- 然后设置子元素为绝对定位，设置top为50%；再设置 `transform:translateY(-50%);`
- 优点：居中元素不会对其他的产生影响
- 缺点：transfrom兼容性问题
```css
.parent {
    position: relative;
}

.child {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
}
```

## 方法三
- 父元素设置弹性盒子，再设置对齐 `align-items:center;`
- 优点：简单快捷
- 缺点：兼容性
```css
.parent {
    display: flex;
    align-items: center;
}
.child {
}
```

## 方法四
- 父元素设置高度，再使用line-height来垂直居中
```css
.parent {
    height: 100px;
    line-height: 100px;
}

.child {
}
```

## 方法五
- 将父元素设置为网格布局，再设置`align-items:center;` 或`align-content:center;`

```css
 .parent {
    display:grid;
    align-items:center;
    /*align-content:center;*/
}

.child {
}
```

## 方法六：
- 将父元素设置为网格布局，子元素再设置`align-self:center;`或者`margin: auto 0`

```css
 .parent {
    display:grid;
    
}

.child {
    align-self:center;
}
```

## 方法七：
- 首先设置父元素为网格布局，然后子元素设置`align-self: center; `或者`margin: auto 0;`
```css
.parent {
    display: grid;
}

.child {
    align-self: center;
    /**margin: auto 0;**/
}
```
